WIP: Fixed problem with changing order when using DeDupFilter
seecr/meresco-lucene pull request #1
Opened 2019-01-15 15:13 UTC by vwolf010

2019-01-16 08:34 UTC, jurjanpaul requested changes
Mooie werkende oplossing om verspringende zoekresultaten tegen te gaan door het 'beste' zoekresultaat per 'common key' uitgesteld per segment aan delegate.collect te voeren (als alle resultaten gezien zijn).

Issue: Het keyveld van de ZP summary index wordt nu hard genoemd en dat is niet acceptabel. (Reden om het te introduceren: deterministisch een representant kiezen uit meerdere resultaten met dezelfde waarde voor het sortByField). De uitdaging is dat DeDupCollector geen notie heeft van deze keys en de aanroepende class Lucene ook niet. Het alternatief om docId te gebruiken is alleen deterministisch binnen één Lucene index (dus niet over meerdere indexen; hmm... ook niet echt binnen 1 index, aangezien docIds na merges veranderen) en valt daarom af. Een functionele oplossing is om in het geval van meerdere resultaten met zelfde sortByValue een String compare te doen op de inhoud van het stored __id__ veld, maar dat zou wel eens behoorlijk duur kunnen zijn... Ik wil dit zelf de komende tijd onderzoeken, maar weet nog niet precies wanneer/hoe snel ik daar aan toe kom.

Issue/wens: in plaats van de beste representant (praktisch 'meest recente') aan delegate te voeren, willen we de best scorende doorgeven aan de scorer. (Anders zorgt een nieuwe uitgave van een boek ervoor dat het betreffende 'cluster' naar beneden gedrukt wordt in de zoekresultaten in het geval de metadata van de nieuwe uitgave minder rijk is.) Het is alleen nog de vraag hoe duur het wordt om de score hier te bepalen. [Deze wens kan beschouwd worden als los issue met losse commit(s).]

2019-02-07 11:11 UTC, jurjanpaul requested changes
Tof dat nieuwe aanpak werkt!

Qua code veel goede verbeteringen (o.a. duidelijkere naamgeving)!

Nu toch nog even een paar punten die ik nog graag aangepast zou zien:
- binnen meresco/lucene zijn alleen whitespace wijzigingen ge-commit. Liever terugdraaien (want heeft niets met de bugfix te maken).

In DeDupFilterSuperCollector
- sortByValue zou nu (in elk geval intern) beter gewoon sortByValues kunnen heten (dus ook in QueryData)
- idem voor sortByFieldName => sortByFieldNames
- mij nog onduidelijk waarom Key nu parameters (en fields) enumeratedKeyValue en baseId heeft. Kunnen ze weg (of zie ik dat toch verkeerd)?

- Misschien had je het uitgelegd maar ik ben toch even in de war over waarom `this.delegate.setNextReader(context);` kon verdwijnen uit DeDupFilterSubCollector.doSetNextReader

- De aanpassingen in SuperIndexSearcher, hoe aantrekkelijk op het oog ze ook zijn, hebben in feite niets met het probleem te maken en hadden dus ook beter niet in deze patch kunnen zitten. Nu moet ik er toch weer over nadenken, terwijl ik half-half een vermoeden houdt dat de oorspronkelijke committer bewust voor de bestaande aanpak had gekozen om 1 taak op de huidige thread uit te voeren. Tja.

- Iets dergelijks geldt voor src/org/meresco/lucene/search/TopDocSuperCollector.java
Ik begrijp de (noodzaak voor de) aanpassing niet goed.
Mogelijk is de aanpassing in 'topDocs' niet echt nodig, maar in 'getTotalHits' wel. Kun je dit toelichten (om m'n geheugen op te frissen)?

In Lucene.java
- De check op totalHits==0 respectievelijk adjustedTotalHits==0 vind ik niet fraai. Eigenlijk lijken ze me op dit moment allebei overbodig, maar anders zou ik een vergelijking met -1 (not yet set to a meaningful value) logischer/duidelijker vinden. Maar nogmaals: zonder die guards zou ik de code leesbaarder vinden. Zie ik een performance penalty over het hoofd?

- 'topDocsResponse' begint nu met collectors.topCollector.getTotalHits(), waarvan we de returnwaarde blijkbaar eerder ook al niet gebruikten. Weet jij of het hier om het side effect gaat? In dat geval zou het tof zijn als dat op z'n minst in een minimaal commentaar expliciet gemaakt zou worden. Of is de hele regel toch gewoon overbodig (lijkt mij)?

- (Waarom zoveel lege regels aan het begin van deze methode (en later binnen de loop)? helpt niet met de leesbaarheid ofzo)

- workId hernoemen naar deDupValue of zoiets.

2019-02-11 09:03 UTC, vwolf010 commented
> Tof dat nieuwe aanpak werkt!
> 
> Qua code veel goede verbeteringen (o.a. duidelijkere naamgeving)!
> 
> Nu toch nog even een paar punten die ik nog graag aangepast zou zien:
> 
> * binnen meresco/lucene zijn alleen whitespace wijzigingen ge-commit. 
> Liever terugdraaien (want heeft niets met de bugfix te maken).
Eens.

> In DeDupFilterSuperCollector
> 
> * sortByValue zou nu (in elk geval intern) beter gewoon sortByValues kunnen heten (dus ook in QueryData)
Eens.

> * idem voor sortByFieldName => sortByFieldNames
Eens.

> * mij nog onduidelijk waarom Key nu parameters (en fields) enumeratedKeyValue en baseId heeft. Kunnen ze weg (of zie ik dat toch verkeerd)?

Was voorheen nodig omdat ik hier iets mee deed, maar na een koerswijziging zijn deze velden inderdaad weer obsolete geworden.

> * Misschien had je het uitgelegd maar ik ben toch even in de war over waarom `this.delegate.setNextReader(context);` kon verdwijnen uit DeDupFilterSubCollector.doSetNextReader

We hebben hier samen naar gekeken en het leek jou ook overbodig. Deze method verwerkt geen data maar is enkel een initializer. Deze 2x aanroepen heeft geen zin. Door het weghalen zijn ook geen testen omgevallen dus het lijkt erop dat de 2e call inderdaad overbodig was.

> * De aanpassingen in SuperIndexSearcher, hoe aantrekkelijk op het oog ze ook zijn, hebben in feite niets met het probleem te maken en hadden dus ook beter niet in deze patch kunnen zitten. Nu moet ik er toch weer over nadenken, terwijl ik half-half een vermoeden houdt dat de oorspronkelijke committer bewust voor de bestaande aanpak had gekozen om 1 taak op de huidige thread uit te voeren. Tja.

Ik heb de oude code weer teruggezet omdat het functioneel geen verschil maakt en ik hier niet te lang meer bij stil wil staan. Maar het lijkt mij dat mijn versie duidelijker was. En ja, misschien scheelt het in het aanmaken van 1 extra thread, maar het lijkt mij niet dat dit op deze plek heel veel performance scheelt en dan zou ik zelf toch hebben gekozen voor een "didactisch" betere opzet.

> * Iets dergelijks geldt voor src/org/meresco/lucene/search/TopDocSuperCollector.java
>   Ik begrijp de (noodzaak voor de) aanpassing niet goed.
>   Mogelijk is de aanpassing in 'topDocs' niet echt nodig, maar in 'getTotalHits' wel. Kun je dit toelichten (om m'n geheugen op te frissen)?

getTotalHits() deed een aanroep topDocs(0). Deze call moest eerst een merge doen van alle topDocs om daarna de totalHits eruit te kunnen halen. Dit is niet nodig want je kan ook met een simpele iterator over de subCollectors heen gaan en dan hoef je geen kostbare merge van de topDocs te doen. Later in Lucent.topDocsResponse wordt topDocs(x) wederom aangeroepen en werden de topDocs wederom gemerged (in de huidige versie dus voor de 1e keer).

Verder vind ik de code van de topDocs() method zelf helderder omdat het grote verschil zit in wel of geen sort gebruiken en dit heb ik nu heel expliciet gemaakt.

> In Lucene.java
> 
> * De check op totalHits==0 respectievelijk adjustedTotalHits==0 vind ik niet fraai. Eigenlijk lijken ze me op dit moment allebei overbodig, maar anders zou ik een vergelijking met -1 (not yet set to a meaningful value) logischer/duidelijker vinden. Maar nogmaals: zonder die guards zou ik de code leesbaarder vinden. Zie ik een performance penalty over het hoofd?

Zoals besproken, opgelost door een expliciete isFirstLoop boolean te introduceren.

> * 'topDocsResponse' begint nu met collectors.topCollector.getTotalHits(), waarvan we de returnwaarde blijkbaar eerder ook al niet gebruikten. Weet jij of het hier om het side effect gaat? In dat geval zou het tof zijn als dat op z'n minst in een minimaal commentaar expliciet gemaakt zou worden. Of is de hele regel toch gewoon overbodig (lijkt mij)?

Goed gezien, had vroeger denk ik wel een side effect (impliciete merge van topDocs) maar is nu overbodig geworden.

> * (Waarom zoveel lege regels aan het begin van deze methode (en later binnen de loop)? helpt niet met de leesbaarheid ofzo)

Da's een kwestie van smaak, het is nu aangepast aan jouw smaak.

> * workId hernoemen naar deDupValue of zoiets.
Done.

2019-02-12 09:54 UTC, jurjanpaul approved these changes

2019-02-12 10:08 UTC, closed without merging